name = "DE9IM"
uuid = "5483dedb-0874-478e-8d7a-8c665bf87f01"
authors = ["Rafael Schouten <rafaelschouten@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
